var Web3 = require('web3');
var fs = require('fs');

var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

var coinbase = web3.eth.coinbase;
console.log(coinbase);
web3.eth.defaultAccount = coinbase;
var balance = web3.eth.getBalance(coinbase);
console.log(balance.toString(10));
// solidity code code
fs.readFile('smartcontracts/cpuapi-contract.sol', function(err, data) {
console.log('data from solidity file');
console.log(data.toString());
  var source = data.toString();
console.log('after source');
var compiled = web3.eth.compile.solidity(source);
var keye = Object.keys(compiled);
var code = compiled[keye[0]].code;
// contract json abi, this is autogenerated using solc CLI
var abi = compiled[keye[0]].info.abiDefinition;

var myContract;
//  var blockwatch = web3.eth.filter('latest');
//console.log(blockwatch);

  web3.eth.contract(abi).new({data: code, gas: 1700000,}, function (err, contract) {

    if (err) {
console.error(err);
      return;
    }
    else if(contract.address) {
      myContract = contract;
      console.log('address: ' + myContract.address);
      console.log('start fo rtrererennnnsns');
      myContract.setComputeStart('0x9f673838e8bbacf9455742be2cc2e3ec99afc2ea');
      myContract.setComputeStop('0x9f673838e8bbacf9455742be2cc2e3ec99afc2ea');

    }
  });

});
