var Web3 = require('web3');
var fs = require('fs');

var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

var coinbase = web3.eth.coinbase;
console.log(coinbase);
web3.eth.defaultAccount = coinbase;
var balance = web3.eth.getBalance(coinbase);
console.log(balance.toString(10));
console.log(balance);
// solidity code code
fs.readFile('smartcontracts/dmap-contract.sol', function(err, data) {
console.log('data from solidity file');
//console.log(data.toString());
  var source = data.toString();

var compiled = web3.eth.compile.solidity(source);
var keye = Object.keys(compiled);
var code = compiled[keye[0]].code;
// contract json abi, this is autogenerated using solc CLI
var abi = compiled[keye[0]].info.abiDefinition;

//console.log('that abi ===');
//console.log(abi);

var myContract;
console.log('start recall process');
	var myContract = web3.eth.contract(abi);
	var myContract = myContract.at('0xe55817eb366a777663560c6310f50b3baad05268');
//console.log(mysamplingContract);
    console.log('start fo rtrererennnnsns');
  var returnName = myContract.getDmapDetail();
console.log(returnName);
console.log('after');
var returnNamech = myContract.getDmapDetailchash();
console.log(returnNamech);
console.log('after');
var returndmodel = myContract.getDataModel();
console.log(returndmodel);
console.log('after');
  var returnOwner = myContract.getDsampling();
console.log(returnOwner);
console.log('after');
  var returnMeasure = myContract.getDscoring();
console.log(returnMeasure);
console.log('after');

  var returnCount = myContract.getDsamplingCount();
console.log(returnCount);
console.log('after');

    // record andother peer sample
    myContract.setDsampling('0x5ff4436b377180d2729e45e1b03e90ad4805cbab');
    var returnCount = myContract.getDsamplingCount();
  console.log(returnCount);
  console.log('after');
  // record andother peer sample
  myContract.setDsampling('0xe4827d823aeea0017480b87df86aaa3e98d0937e');
  var returnCount = myContract.getDsamplingCount();
console.log(returnCount);
console.log('after');


});
